config/routes.rb
Rails.application.routes.draw do
  root to: 'offers#index'

  get 'search' => 'offers#search'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#failure'
  get 'signout' => 'sessions#destroy', as: 'signout'

  get 'static/index'

end

app/models/location.rb
class Location
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short
  include Mongoid::Timestamps::Updated::Short
  include Geocoder::Model::Mongoid

  geocoded_by :location
  after_validation :geocode, if: ->(obj) { obj.coordinates.nil? }

  field :l, as: :location,    type: String
  field :c, as: :canonical,   type: String
  field :p, as: :coordinates, type: Array

  index({ c: '2d' }, { min: -200, max: 200 })

  DICTIONARY = %w{new ely}

  def location=(location)
    self[:canonical] = Canoniser.canonise(location)

    process_part = -> (string) {
      return string if string.size < 4 && DICTIONARY.none? { |dict| dict == string.downcase }
      string.downcase.titleize
    }

    super location.split(' ').map(&process_part).join(' ')
  end

  class Canoniser
    def initialize(string)
      @string = string
    end

    class << self
      def canonise(string)
        new(string).canonise
      end
    end

    def canonise
      @canonised ||= process_string
    end

    private

    def process_string
      @string.delete(',').upcase
    end
  end

  class Lookup
    def initialize(location_string)
      @location_string = location_string
    end

    def self.for(location_string)
      new(location_string)
    end

    def location
      Location.find_or_create_by(canonical: canonise) do |location|
        location.location = @location_string
      end
    end

    private

    def canonise
      Canoniser.canonise(@location_string)
    end
  end
end

app/models/offer.rb
class Offer
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short
  include Mongoid::Timestamps::Updated::Short

  attr_accessor :distance

  field :t, as: :title,        type: String
  field :p, as: :published_at, type: Time

  field :l, as: :location,    type: String
  field :c, as: :coordinates, type: Array

  index({ c: '2d' }, { min: -200, max: 200 })
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps::Created::Short
  include Mongoid::Timestamps::Updated::Short

  field :p, as: :provider,  type: String
  field :u, as: :uid,       type: String
  field :n, as: :name,      type: String
  field :i, as: :image_url, type: String

  field :t, as: :oauth_token,      type: String
  field :e, as: :oauth_expires_at, type: Time

  def logged_in?
    true
  end

  class << self
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.image_url = auth.info.image
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end

    def fetch(id)
      begin
        find(id)
      rescue Mongoid::Errors::DocumentNotFound, Mongoid::Errors::InvalidFind
        Anonymous.new
      end
    end
  end
  
  class Anonymous
    def name
      'Anonymous'
    end

    def logged_in?
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= find_user
  end
  helper_method :current_user

  def find_user
    User.fetch(session[:user_id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.order_by(:published_at.desc)
      .page(params[:page])
  end

  def search
    @offers = Searcher.for_params(params).results(page: params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id.to_s
    flash[:success] = "Welcome #{user.name}. You have signed in successfully!"
    redirect_to previous_page
  end

  def failure
    flash[:error] = 'Oh snap... Something went wrong. Please try again.'
    redirect_to previous_page
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private

  def previous_page
    request.env['omniauth.origin'] || root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offer_helper.rb
module OfferHelper
  def distance_for(offer)
    return '< 5 mi' if offer.distance < 5
    offer.distance.to_f.round(2).to_s + ' mi'
  end

  def format_distance_for(offer)
    content_tag(:em, distance_for(offer), { class: 'distance' }) unless offer.distance.nil?
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<% if flash[:success].present? %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "EM", root_path, { class: 'navbar-brand' } %>
    </div>

    <%= render "layouts/nav/search_form" %>

    <div class="nav navbar-right">
      <% if current_user.logged_in? %>
        <p class="navbar-text">
          Welcome <%= current_user.name %>,
          <%= link_to "Sign out", signout_path, { id: 'logout-btn' } %>
        </p>
      <% else %>
        <%= content_tag(:a, fa_icon("facebook", text: "Sign In"), { 
          id:    'login-btn',
          href:  '/auth/facebook',
          class: 'btn btn-primary navbar-btn',
        }) %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EMarket</title>
  <% if Rails.env.production? %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" />
  <% else %>
    <%= stylesheet_link_tag 'bootstrap_base', media: 'all', 'data-turbolinks-track' => true %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/nav" %>
  <%= render "layouts/flash_messages" %>

<%= yield %>

</body>
</html>

app/views/layouts/nav/_search_form.html.erb
<%= form_tag search_path, { enforce_utf8: false, method: 'get', id: 'search-form', class: 'navbar-form navbar-left', role: 'search' } do %>
  <%= content_tag(:div, { class: 'form-group' }) do -%>
    <%= text_field_tag(:query, params['query'], { id: 'query', class: 'form-control', placeholder: 'Search...' }) %>
  <% end -%>
  <%= content_tag(:div, { class: 'form-group' }) do -%>
    <%= text_field_tag(:location, params['location'], { id: 'location', class: 'form-control', placeholder: 'near post code or city...' }) %>
  <% end -%>
  <%= button_tag("Search", { type: 'submit', name: nil, class: 'btn btn-default' }) %>
<% end %>

app/views/offers/_offer.html.erb
<div class="offer">
  <h3><%= offer.title %></h3>
  <small><%= offer.published_at %></small>
  <%= format_distance_for offer %>
</div>

app/views/offers/_offers.html.erb
<div class="offers">
  <% for offer in @offers %>
    <%= render 'offer', { offer: offer } %>
  <% end %>
</div>

app/views/offers/index.html.erb
<%= render 'offers', { offers: @offers } %>

<%= paginate @offers %>

app/views/offers/search.html.erb
<%= render 'offers', { offers: @offers } %>

<%= paginate @offers %>